env:
  action_space:
    num_voltages: 2
    voltage_range:
    - -5.0
    - 5.0
  max_steps: 50
  observation_space:
    channels: 1
    dtype: float32
    image_size:
    - 128
    - 128
    normalization_range:
    - 0.0
    - 1.0
  reward: null
  tolerance: 0.5
simulator:
  measurement:
    fixed_gate_voltages:
      max: 1.0
      min: -1.0
    fixed_gates:
    - 0
    - 3
    - 4
    optimal_VG_center:
    - 1
    - 1
    - 1
    - 1
    - 0.4
    resolution: 200
    sensor_gate_voltage:
      max: 1.0
      min: 0.5
    swept_gates:
    - 1
    - 2
    v_max: 2.0
    v_min: -2.0
  model:
    Cdd:
      diagonal: 0
      furthest:
        max: 0.015
        min: 0.005
      nearest_neighbor:
        max: 0.35
        min: 0.25
      next_nearest:
        max: 0.07
        min: 0.03
    Cds:
    - max: 0.08
      min: 0.05
    - max: 0.08
      min: 0.05
    - max: 0.08
      min: 0.05
    - max: 0.08
      min: 0.05
    Cgd:
    - - max: 1.0
        min: 0.8
      - max: 0.45
        min: 0.15
      - max: 0.2
        min: 0.13
      - max: 0.015
        min: 0.005
      - max: 0.03
        min: 0.01
    - - max: 0.45
        min: 0.15
      - max: 1.0
        min: 0.8
      - max: 0.45
        min: 0.15
      - max: 0.2
        min: 0.13
      - max: 0.03
        min: 0.01
    - - max: 0.2
        min: 0.13
      - max: 0.45
        min: 0.15
      - max: 1.0
        min: 0.8
      - max: 0.45
        min: 0.15
      - max: 0.03
        min: 0.01
    - - max: 0.015
        min: 0.005
      - max: 0.2
        min: 0.13
      - max: 0.45
        min: 0.15
      - max: 1.0
        min: 0.8
      - max: 0.03
        min: 0.01
    Cgs:
    - max: 0.05
      min: 0.0
    - max: 0.05
      min: 0.0
    - max: 0.05
      min: 0.0
    - max: 0.05
      min: 0.0
    - max: 1.0
      min: 0.8
    T:
      max: 50
      min: 10
    algorithm: default
    coulomb_peak_width:
      max: 0.31
      min: 0.3
    implementation: rust
    latching_model_parameters:
      Exists: true
      n_dots: 4
      p_inter:
        max: 1.0
        min: 0.2
      p_leads:
        max: 1.0
        min: 0.2
    max_charge_carriers: 7
    telegraph_noise_parameters:
      amplitude:
        max: 0.012
        min: 0.0
      p01:
        max: 0.01
        min: 0.0
      p10_factor:
        max: 100
        min: 0
    white_noise_amplitude:
      max: 0.01
      min: 0.0
  virtual_gate_matrix:
  - - 1
    - 0
    - 0
    - 0
    - 0
  - - 0
    - 1
    - 0
    - 0
    - 0
  - - 0
    - 0
    - 1
    - 0
    - 0
  - - 0
    - 0
    - 0
    - 1
    - 0
  - - 0
    - 0
    - 0
    - 0
    - 1
training:
  debug: true
  render_fps: 10
  render_mode: human
  seed: 42
