# This file contains all parameters for the base qarray simulator

simulator:
  model:
    # Capacitance matrices for quantum dots
    # All capacitance values are normalized and dimensionless
    
    # Dot-to-dot capacitance matrix (Cdd) - symmetric coupling between quantum dots
    # Coupling strength depends on physical distance between dots
    Cdd:
      # Self-capacitance (diagonal elements) - normalized to 0
      diagonal: 0
      # Distance-based coupling rules (exponentially decaying with distance)
      distance_coupling:
        # Distance 1: adjacent dots (strongest coupling)
        1: {"min": 0.25, "max": 0.35}
        # Distance 2: next-nearest neighbors  
        2: {"min": 0.03, "max": 0.07}
        # Distance 3+: long-range coupling (weakest)
        3_plus: {"min": 0.005, "max": 0.015}
    
    # Gate-to-dot capacitance matrix (Cgd) - coupling between gates and quantum dots
    # Uses distance-based rules for scalability
    Cgd:
      # Primary coupling: gate directly controls its corresponding dot
      primary_coupling: {"min": 0.8, "max": 1.0}
      # Cross-coupling based on distance between gate and non-primary dots
      cross_coupling:
        # Distance 1: adjacent gate-dot pairs
        1: {"min": 0.25, "max": 0.45}
        # Distance 2: next-adjacent gate-dot pairs
        2: {"min": 0.1, "max": 0.2}  
        # Distance 3+: long-range gate-dot coupling
        3_plus: {"min": 0.005, "max": 0.015}
      # Sensor gate coupling to all dots (typically weaker and uniform)
      sensor_coupling: {"min": 0.02, "max": 0.04}
    
    # Dot-to-sensor capacitance (Cds) - how quantum dots couple to charge sensor
    Cds:
      dots: {"min": 0.05, "max": 0.08}
    
    # Gate-to-sensor capacitance (Cgs) - how gates affect charge sensor
    Cgs:
      # Plunger gates to sensor (typically weak coupling)
      plunger_gates: {"min": 0.0, "max": 0.05}
      # Sensor gate to sensor (strong direct coupling)
      sensor_gate: {"min": 0.8, "max": 1.0}
    
    # White noise amplitude for charge stability diagram
    white_noise_amplitude: {"min": 0.000, "max": 0.0001}
    
    # Telegraph noise parameters (random telegraph noise)
    telegraph_noise_parameters:
      p01: {"min": 0.0, "max": 0.01}  # Probability of transition from 0 to 1
      p10_factor: {"min": 0, "max": 100}    # Factor for probability of transition from 1 to 0
      amplitude: {"min": 0.0, "max": 0.0012}  # Amplitude of telegraph noise
    
    # Latching model parameters for charge state transitions
    latching_model_parameters:
      Exists: False 
      n_dots: 2     # Number of quantum dots
      p_leads: {"min": 0.2, "max": 1.0}  # Lead coupling probabilities
      p_inter: {"min": 0.2, "max": 1.0}  # Inter-dot coupling probabilities
    
    # Temperature in mK
    T: {"min": 50, "max": 200}
    
    # Width of coulomb peaks
    coulomb_peak_width: {"min": 0.1, "max": 0.2}
    
    # Base tunnel coupling for TunnelCoupledChargeSensed
    tc: {"min": 0.1, "max": 0.2}
    
    # Barrier-to-dot capacitance matrix (Cbd) - (n_dot, n_barrier) matrix
    Cbd:
      distance_coupling:
        1: {"min": 0.04, "max": 0.08}    # Adjacent barrier-dot
        2: {"min": 0.01, "max": 0.03}    # Next-adjacent barrier-dot  
        3_plus: {"min": 0.005, "max": 0.015}  # Long-range barrier-dot
    
    # Barrier-to-gate capacitance matrix (Cbg) - (n_barrier, n_gate) matrix  
    Cbg:
      distance_coupling:
        1: {"min": 0.08, "max": 0.15}    # Adjacent barrier-gate
        2: {"min": 0.03, "max": 0.18}    # Next-adjacent barrier-gate
        3_plus: {"min": 0.01, "max": 0.03}  # Long-range barrier-gate
    
    # Barrier-to-sensor capacitance matrix (Cbs) - (n_sensor, n_barrier) matrix
    Cbs:
      coupling: {"min": 0.0003, "max": 0.001}
    
    # Barrier-to-barrier capacitance matrix (Cbb) - (n_barrier, n_barrier) matrix
    Cbb:
      diagonal: 1.0  # Self-capacitance 
      distance_coupling:
        1: {"min": 0.03, "max": 0.08}    # Adjacent barriers
        2: {"min": 0.01, "max": 0.03}    # Next-adjacent barriers
        3_plus: {"min": 0.005, "max": 0.015}  # Long-range barriers
    
    # Barrier voltage model parameters for tunnel coupling control
    barrier_model:
      tc_base: {"min": 0.1, "max": 0.2}        # Base tunnel coupling
      alpha_per_barrier: {"min": 0.8, "max": 2.0}  # Exponential scaling per barrier
    
    # Voltage-dependent capacitance model parameters
    voltage_capacitance_model:
      alpha: {"min": 0.05, "max": 0.15}  # Cdd voltage dependence (5-15%)
      beta: {"min": 0.05, "max": 0.15}   # Cgd voltage dependence (5-15%)

    # Algorithm for charge stability diagram
    algorithm: "default"
    # Implementation for charge stability diagram
    implementation: "jax"
    # Maximum number of charge carriers
    max_charge_carriers: 4

  measurement:
    #model.optimal_Vg(center) gives the optimal gate voltage in volts from desired charge occupancy
    optimal_VG_center: {"dots": 1.0, "sensor": 0.45}

    #target tunnel coupling
    tc: 1e-4

