"""
Script to generate 25 ground truth scans from the qarray environment.
Each scan is generated by:
1. Resetting the environment to get random parameters
2. Setting barrier voltages to zero
3. Setting plunger voltages to their ground truth values
4. Extracting the scan between the first two pair of dots
"""

import os
import sys
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# Add src directory to path
src_dir = Path(__file__).parent.parent.parent
sys.path.insert(0, str(src_dir))

from swarm.environment.env import QuantumDeviceEnv


def generate_ground_truth_scans(num_scans=25, output_file="ground_truth_scans.png"):
    """
    Generate ground truth scans and save them in a grid.

    Args:
        num_scans: Number of scans to generate (default: 25 for 5x5 grid)
        output_file: Output filename for the grid image
    """
    # Initialize environment
    env = QuantumDeviceEnv(training=True)

    # Calculate grid dimensions
    grid_size = int(np.sqrt(num_scans))
    if grid_size * grid_size != num_scans:
        raise ValueError(f"num_scans must be a perfect square, got {num_scans}")

    scans = []

    print(f"Generating {num_scans} ground truth scans...")

    for i in range(num_scans):
        # Reset environment to get random parameters
        obs, info = env.reset()

        # Get ground truth plunger voltages from device state
        gate_ground_truth = env.device_state["gate_ground_truth"]

        # Set barrier voltages to zero
        if env.use_barriers:
            barrier_voltages = np.zeros(env.num_barrier_voltages)
        else:
            barrier_voltages = None

        # Generate observation with ground truth plunger voltages and zero barriers
        raw_obs = env.array._get_obs(gate_ground_truth, barrier_voltages)

        # Extract scan between first two dots (first channel)
        scan = raw_obs["image"][:, :, 0]

        scans.append(scan)
        print(f"Generated scan {i+1}/{num_scans}")

    # Create figure with grid layout
    fig, axes = plt.subplots(grid_size, grid_size, figsize=(15, 15))
    fig.suptitle("Ground Truth Scans (First Two Dots)", fontsize=16)

    # Plot each scan
    for idx, (ax, scan) in enumerate(zip(axes.flat, scans)):
        im = ax.imshow(scan, origin="lower", aspect="auto", cmap="viridis")
        ax.set_title(f"Scan {idx+1}", fontsize=10)
        ax.axis("off")

    # Adjust layout to prevent overlap
    plt.tight_layout()

    # Save figure
    output_path = os.path.join(os.path.dirname(__file__), output_file)
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"\nSaved grid of scans to: {output_path}")

    plt.close()


if __name__ == "__main__":
    generate_ground_truth_scans()
