# Environment Configuration
# This file contains all parameters for the quantum device simulator and RL environment

simulator:
  model:
    # Capacitance matrices for quantum dots (dot-to-dot coupling)
    Cdd: {"min": 0.08, "max": 0.5}
    
    # Gate-to-dot capacitance matrix
    Cgd:
      - [{"min": 0.7, "max": 1.0}, {"min": 0.0, "max": 0.35}, {"min": 0.0, "max": 0.1}]
      - [{"min": 0.0, "max": 0.35}, {"min": 0.7, "max": 1.0}, {"min": 0.0, "max": 0.1}]
    
    # Dot-to-sensor capacitance matrix
    Cds: [[0.03, 0.08]]
    
    # Gate-to-sensor capacitance matrix
    Cgs: [[0.03, 0.03, 1]]
    
    # White noise amplitude for charge stability diagram
    white_noise_amplitude: {"min": 0.00, "max": 0.05}
    
    # Telegraph noise parameters (random telegraph noise)
    telegraph_noise_parameters:
      p01: {"min": 0.0, "max": 0.01}  # Probability of transition from 0 to 1
      p10_factor: {"min": 0, "max": 100}    # Factor for probability of transition from 1 to 0
      amplitude: {"min": 0.0, "max": 0.012}  # Amplitude of telegraph noise
    
    # Latching model parameters for charge state transitions
    latching_model_parameters:
      Exists: True #not used
      n_dots: 2     # Number of quantum dots
      p_leads: {"min": 0.2, "max": 1.0}  # Lead coupling probabilities
      p_inter: {"min": 0.2, "max": 1.0}  # Inter-dot coupling probabilities
    
    # Temperature in mK
    T: {"min": 50, "max": 100}
    
    # Width of coulomb peaks
    coulomb_peak_width: {"min": 0.1, "max": 0.2}

    # Algorithm for charge stability diagram
    algorithm: "default"
    # Implementation for charge stability diagram
    implementation: "rust"
    # Maximum number of charge carriers
    max_charge_carriers: 7

  measurement:
    # Voltage sweep ranges for charge stability diagram
    v_min: -2.0
    v_max: 2.0

    resolution: 128
    
    # Optimal gate voltage center for target state, note this is not in volts but in charge occupancy
    #model.optimal_Vg(center) gives the optimal gate voltage in volts from desired charge occupancy
    optimal_VG_center: [1, 1, 0.65]


env:
  # Maximum number of steps per episode
  max_steps: 50
  
  action_space:
    num_voltages: 2  #No longer easy to change, hardcoded in a few places
    voltage_range: [-5.0, 5.0]
  
  observation_space:
    image_size: [128, 128]
    channels: 1
    normalization_range: [0.0, 1.0]
    dtype: "float32"
  
  reward:
  
  #tolerance for termination criteria
  tolerance: 0.5


training:
  # Random seed for reproducibility
  seed: 42
  # Enable debug mode
  debug: false
  # Frames per second for rendering
  render_fps: 10 
  # Render mode
  render_mode: "human"