# Environment Configuration
# This file contains all parameters for the quantum device simulator and RL environment

simulator:
  model:
    # Capacitance matrices for quantum dots (dot-to-dot coupling)
    Cdd: [[1, 0.2], [0.2, 1]]
    
    # Gate-to-dot capacitance matrix
    Cgd:
      - [0.75, 0.1, 0.02]
      - [0.1, 0.75, 0.02]
    
    # Dot-to-source capacitance matrix
    Cds: [[0.08, 0.08]]
    
    # Gate-to-source capacitance matrix
    Cgs: [[0.03, 0.03, 1]]
    
    # White noise amplitude for charge stability diagram
    white_noise_amplitude: 0.001
    
    # Telegraph noise parameters (random telegraph noise)
    telegraph_noise_parameters:
      p01: 0.005  # Probability of transition from 0 to 1
      p10: 0.1    # Probability of transition from 1 to 0
      amplitude: 0.02  # Amplitude of telegraph noise
    
    # Latching model parameters for charge state transitions
    latching_model_parameters:
      Exists: false  # Whether latching model is enabled
      n_dots: 2     # Number of quantum dots
      p_leads: [0.5, 0.5]  # Lead coupling probabilities
      p_inter: [[0.0, 0.8], [0.8, 0.0]]  # Inter-dot coupling probabilities
    
    # Temperature in mK
    T: 50.0
    
    # Width of coulomb peaks
    coulomb_peak_width: 0.2

    # Algorithm for charge stability diagram
    algorithm: "default"
    # Implementation for charge stability diagram
    implementation: "rust"
    # Maximum number of charge carriers
    max_charge_carriers: 7

  measurement:
    # Voltage sweep ranges for charge stability diagram
    v_min: -2.0
    v_max: 2.0

    resolution: 128
    
    # Optimal gate voltage center for target state, note this is not in volts but in charge occupancy
    #model.optimal_Vg(center) gives the optimal gate voltage in volts from desired charge occupancy
    optimal_VG_center: [1, 1, 0.65]

  # Virtual gate transformation matrix
  virtual_gate_matrix:
    - [1, -0.0, 0]
    - [-0.0, 1, 0]
    - [-0.05, -0.05, 0]

env:
  # Maximum number of steps per episode
  max_steps: 50
  
  action_space:
    num_voltages: 2  #No longer easy to change, hardcoded in a few places
    voltage_range: [-10.0, 2.0]
  
  observation_space:
    image_size: [128, 128]
    channels: 1
    normalization_range: [0.0, 1.0]
    dtype: "float32"
  
  reward:
  
  #tolerance for termination criteria
  tolerance: 0.2


training:
  # Random seed for reproducibility
  seed: 42
  # Enable debug mode
  debug: false
  # Frames per second for rendering
  render_fps: 10 
  # Render mode
  render_mode: "human"