training:
  seed: null
  debug: false
  max_episode_steps: 50
  render_mode: rgb_array
  render_fps: 30

env:
  tolerance: 0.02
  target_center: [0.0, 0.0]
  action_space:
    barrier_names: [barrier_2, barrier_3, barrier_4]
    barrier_range: [-1.0, 1.0]
    plunger_range: [-0.2, 0.2]
    clip_actions: true
  observation_space:
    image_size: [64, 64]
    channels: 1
    dtype: uint8
    include_voltages: true

simulator:
  measurement:
    window_size: [0.2, 0.2]
    resolution: 64
    use_sensor_signal: true
    compensate_sensors: true
    compute_polytopes: false
  barrier: {}  # placeholder to optionally override qdarts barrier config

reward:
  type: distance_to_target
  success_threshold: 0.02
  weights:
    distance_weight: 0.1
    step_penalty: 0.1
    success_bonus: 200.0 