# QDarts Configuration for Quantum Device Simulation
# This file contains all parameters for the QDarts simulator

device:
  # Device topology
  topology:
    num_dots: 3
    num_gates: 6
    inner_dots: [0, 1]
    sensor_dots: [2]
    dot_plungers: [0, 1]
    barrier_plungers: [2, 3, 4]
    sensor_plungers: [5]

  # Target state configuration
  target_state: [1, 1, 5]

simulator:
  capacitance:
    # Dot-to-dot capacitance matrix (N_dots x N_dots)
    C_DD:
      - [1.0, 0.2, 0.08]
      - [0.2, 1.0, 0.08]
      - [0.08, 0.08, 1.0]
    
    # Dot-to-gate capacitance matrix (N_dots x N_gates)
    C_DG:
      - [0.75, 0.1, 0, 0, 0, 0.02]
      - [0.1, 0.75, 0, 0, 0, 0.02]
      - [0, 0, 0, 0, 0, 1.0]
    
    # Minimum voltage bounds for each gate
    bounds_limits: -2.0
    
    # Deviation from constant interaction model
    ks: 4

  tunneling:
    # Enable tunneling simulation
    enabled: true
    
    # Temperature in meV
    temperature: 0.2
    
    # Tunnel coupling matrix (N_dots x N_dots)
    couplings:
      - [0, 30e-6, 30e-6]
      - [30e-6, 0, 30e-6]
      - [30e-6, 30e-6, 0]

  sensor:
    # Sensor model configuration
    model_type: "NoisySensorDot"
    
    # Peak configuration
    g_max: 1.0
    peak_width_multiplier: 150
    
    # Noise configuration
    noise:
      fast_noise_amplitude: 0.0001 # ueV
      slow_noise_amplitude: 0.0001 # ueV
      correlation_time: 250
      virtual_samples: 200

measurement:
  # Voltage sweep configuration
  voltage_range:
    min: [-0.2, -0.2]
    max: [0.4, 0.4]
  
  # Resolution for 2D scans
  resolution: 250
  
  # Gate configuration matrix for 2D sweeps
  sweep_matrix:
    - [1, 0]  # Gate 0 on x-axis
    - [0, 1]  # Gate 1 on y-axis
    - [0, 0]  # Other gates fixed
    - [0, 0]
    - [0, 0]
    - [0, 0]

output:
  # Plotting configuration
  plots:
    save_format: "png"
    dpi: 300
    bbox_inches: "tight"
  
  # File naming
  filenames:
    csd_plot: "qdarts_csd_plot.png"
    sensor_plot: "qdarts_sensor_plot.png"
    noised_plot: "qdarts_noised_plot.png"

logging:
  # Logging configuration
  print_logs: true
  timing: true
  debug: false 