
# Device Configuration
device:
  topology:
    num_dots: 3
    num_gates: 6
    sensor_dots: [2]
  target_state: [1, 1, 5]

# Simulator Configuration (with ranges for randomization)
simulator:
  capacitance:
    C_DD:
      - [{"min": 0.8, "max": 1.2}, {"min": 0.1, "max": 0.3}, {"min": 0.05, "max": 0.15}]
      - [{"min": 0.1, "max": 0.3}, {"min": 0.8, "max": 1.2}, {"min": 0.05, "max": 0.15}]
      - [{"min": 0.05, "max": 0.15}, {"min": 0.05, "max": 0.15}, {"min": 0.8, "max": 1.2}]
    C_DG:
      - [{"min": 0.6, "max": 0.9}, {"min": 0.05, "max": 0.15}, {"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0.01, "max": 0.03}]
      - [{"min": 0.05, "max": 0.15}, {"min": 0.6, "max": 0.9}, {"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0.01, "max": 0.03}]
      - [{"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0.8, "max": 1.2}]
    bounds_limits: -2.0
    ks: 4
  
  tunneling:
    tunnel_couplings:
      - [{"min": 0, "max": 0}, {"min": 20e-4, "max": 40e-4}, {"min": 0, "max": 0}]
      - [{"min": 20e-4, "max": 40e-4}, {"min": 0, "max": 0}, {"min": 0, "max": 0}]
      - [{"min": 0, "max": 0}, {"min": 0, "max": 0}, {"min": 0, "max": 0}]
    temperature: {"min": 0.5, "max": 2.0}
    energy_range_factor: {"min": 5.0, "max": 6.0}
  
  barrier:
    # Cutoff threshold for "effectively zero" tunnel couplings
    cutoff_coupling_abs: 3e-5
    barrier_mappings:
      barrier_2:
        coupling_type: "reservoir_to_dot"
        target_dot: 0
        base_coupling: {"min": 20e-4, "max": 40e-4}
        alpha: {"min": 1.5, "max": 2.5}
        voltage_offset: {"min": -0.1, "max": 0.1}
      barrier_3:
        coupling_type: "dot_to_dot"
        target_dots: [0, 1]
        base_coupling: {"min": 20e-4, "max": 40e-4}
        alpha: {"min": 1.0, "max": 2.0}
        voltage_offset: {"min": -0.1, "max": 0.1}
      barrier_4:
        coupling_type: "dot_to_reservoir"
        target_dot: 1
        base_coupling: {"min": 20e-4, "max": 40e-4}
        alpha: {"min": 1.5, "max": 2.5}
        voltage_offset: {"min": -0.1, "max": 0.1}
    default_barrier_voltages:
      barrier_2: 0.0
      barrier_3: 0.0
      barrier_4: 0.0
  
  sensor:
    sensor_dot_indices: [2]
    sensor_gate_indices: [5]
    sensor_detunings: [{"min": 0.0003, "max": 0.0007}]
    noise_amplitude:
      fast_noise: {"min": 5e-5, "max": 2e-4}
      slow_noise: {"min": 5e-6, "max": 2e-5}
    peak_width_multiplier: {"min": 150, "max": 250}

# Measurement Configuration
measurement:
  voltage_range:
    min: [-0.2, -0.2]
    max: [0.2, 0.2]
  resolution: 250
  sweep_matrix:
    - [1, 0]
    - [0, 1]
    - [0, 0]
    - [0, 0]
    - [0, 0]
    - [0, 0]

# Environment Configuration
env:
  max_steps: 50
  action_space:
    plungers:
      num_voltages: 2
      voltage_range: [-2.0, 2.0]
    barriers:
      num_voltages: 3
      voltage_range: [-2.0, 4.0]
  observation_space:
    image_size: "auto"  # Will be set to [resolution, resolution] from measurement
    channels: 1
    normalization_range: [0.0, 1.0]
    dtype: "float32"
    voltage_shape: 5
  tolerance: 0.5

# Training Configuration
training:
  seed: 42
  debug: false
  render_mode: "human" 