env:
  simulator:
    num_dots: 4
    max_steps: 100

    radial_noise:
      enabled: true
      lower: 30
      ramp_range: 5
      total_noise_range: 70

  capacitance_model:
    update_method: null

train:
  rl_config:
    env_runners:
      rollout_fragment_length: 100